[package]
name = "tari_bulletproofs_plus"
version = "0.3.1"
authors = ["The Tari Development Community"]
edition = "2018"
license = "BSD-3-Clause"
description = "A smaller faster implementation of Bulletproofs"

[dependencies]
blake2 = "0.10"
byteorder = { version = "1", default-features = false }
curve25519-dalek = { package = "tari-curve25519-dalek", version = "4.0.3", features = ["serde", "rand_core"] }
derive_more = "0.99"
derivative = "2.2"
digest = { version = "0.10", default-features = false }
itertools = "0.6"
lazy_static = "1.4"
merlin = { version = "3", default-features = false }
rand = "0.8"
# Note: toolchain must be at v1.60+ to support serde v1.0.150+
serde = "1.0"
sha3 = { version = "0.10", default-features = false }
thiserror = { version = "1" }
zeroize = "1"
rand_core = "0.6"

[dev-dependencies]
bincode = "1"
criterion = "0.5"

[[bench]]
name = "range_proof"
harness = false

[[bench]]
name = "generators"
harness = false
